<?php
	header("content-type:text/html;charset=utf-8");
	//接收数据
	$userName=$_POST['userName'];
	$userPass=$_POST['userPass'];
	//数据库处理
		//连接数据库服务器
		$con=mysql_connect("localhost","root","root");
		if(!$con){
			echo("注册失败，服务器异常");
		}else{
			//选择数据库
			mysql_select_db("mobileone",$con);
			//执行sql语句
			$sqlStr="insert into users(userName,userPass) values('".$userName."','".$userPass."')";
			$result=mysql_query($sqlStr,$con);
			//关闭服务器
			mysql_close($con);
			echo($result);
		}
		if($result==1){
			echo("注册成功，去登录吧！");
		}else{
			echo("注册失败……");
		}
?>